[package]
name = "minecraft_server"
version = "0.1.0"
authors = ["Robbe Van Herck <robbe@robbevanherck.be>"]
edition = "2018"

[dependencies]

rayon = "1.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
